server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/seok/git/yml-config-file
        git:
#          uri: file:///Users/seok/Desktop/seok/git/yml-config-file
          uri: https://github.com/msnodeve/spring-cloud-config
#          username: [my username]
#          password: [my password]